window.log=function(){log.history=log.history||[];log.history.push(arguments);if(this.console){arguments.callee=arguments.callee.caller;var e=[].slice.call(arguments);typeof console.log==="object"?log.apply.call(console.log,console,e):console.log.apply(console,e)}};
(function(e){function d(){}for(var h="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,timeStamp,profile,profileEnd,time,timeEnd,trace,warn".split(","),a;a=h.pop();)e[a]=e[a]||d})(function(){try{return console.log(),window.console}catch(e){return window.console={}}}());
(function(e){e.backstretch=function(d,h,a){function j(a){try{u={left:0,top:0},o=k.width(),q=o/m,q>=k.height()?(t=(q-k.height())/2,l.centeredY&&e.extend(u,{top:"-"+t+"px"})):(q=k.height(),o=q*m,t=(o-k.width())/2,l.centeredX&&e.extend(u,{left:"-"+t+"px"})),e("#backstretch, #backstretch img:last").width(o).height(q).filter("img").css(u)}catch(c){}typeof a=="function"&&a()}var i={centeredX:!0,centeredY:!0,speed:0},c=e("#backstretch"),l=c.data("settings")||i;c.data("settings");var k="onorientationchange"in
window?e(document):e(window),m,o,q,t,u;h&&typeof h=="object"&&e.extend(l,h);e(document).ready(function(){if(d){var i;c.length==0?c=e("<div />").attr("id","backstretch").css({left:0,top:0,position:"fixed",overflow:"hidden",zIndex:-999999,margin:0,padding:0,height:"100%",width:"100%"}):c.find("img").addClass("deleteable");i=e("<img />").css({position:"absolute",display:"none",margin:0,padding:0,border:"none",zIndex:-999999}).bind("load",function(d){var b=e(this),g;b.css({width:"auto",height:"auto"});
g=this.width||e(d.target).width();d=this.height||e(d.target).height();m=g/d;j(function(){b.fadeIn(l.speed,function(){c.find(".deleteable").remove();typeof a=="function"&&a()})})}).appendTo(c);e("body #backstretch").length==0&&e("body").append(c);c.data("settings",l);i.attr("src",d);e(window).resize(j)}});return this}})(jQuery);
(function(e){function d(b){e.fn.cycle.debug&&h(b)}function h(){window.console&&console.log&&console.log("[cycle] "+Array.prototype.join.call(arguments," "))}function a(b,g,a){var c=e(b).data("cycle.opts"),d=!!b.cyclePause;d&&c.paused?c.paused(b,c,g,a):!d&&c.resumed&&c.resumed(b,c,g,a)}function j(b,g,r){function d(b,g,a){if(!b&&g===!0){b=e(a).data("cycle.opts");if(!b)return h("options not found, can not resume"),!1;if(a.cycleTimeout)clearTimeout(a.cycleTimeout),a.cycleTimeout=0;q(b.elements,b,1,!b.backwards)}}
if(b.cycleStop==void 0)b.cycleStop=0;if(g===void 0||g===null)g={};if(g.constructor==String)switch(g){case "destroy":case "stop":r=e(b).data("cycle.opts");if(!r)return!1;b.cycleStop++;b.cycleTimeout&&clearTimeout(b.cycleTimeout);b.cycleTimeout=0;r.elements&&e(r.elements).stop();e(b).removeData("cycle.opts");g=="destroy"&&c(r);return!1;case "toggle":return b.cyclePause=b.cyclePause===1?0:1,d(b.cyclePause,r,b),a(b),!1;case "pause":return b.cyclePause=1,a(b),!1;case "resume":return b.cyclePause=0,d(!1,
r,b),a(b),!1;case "prev":case "next":r=e(b).data("cycle.opts");if(!r)return h('options not found, "prev/next" ignored'),!1;e.fn.cycle[g](r);return!1;default:g={fx:g}}else if(g.constructor==Number){var i=g,g=e(b).data("cycle.opts");if(!g)return h("options not found, can not advance slide"),!1;if(i<0||i>=g.elements.length)return h("invalid slide index: "+i),!1;g.nextSlide=i;if(b.cycleTimeout)clearTimeout(b.cycleTimeout),b.cycleTimeout=0;if(typeof r=="string")g.oneTimeFx=r;q(g.elements,g,1,i>=g.currSlide);
return!1}return g}function i(b,g){if(!e.support.opacity&&g.cleartype&&b.style.filter)try{b.style.removeAttribute("filter")}catch(a){}}function c(b){b.next&&e(b.next).unbind(b.prevNextEvent);b.prev&&e(b.prev).unbind(b.prevNextEvent);if(b.pager||b.pagerAnchorBuilder)e.each(b.pagerAnchors||[],function(){this.unbind().remove()});b.pagerAnchors=null;b.destroy&&b.destroy(b)}function l(b,g,c,d,j){var f=e.extend({},e.fn.cycle.defaults,d||{},e.metadata?b.metadata():e.meta?b.data():{}),n=e.isFunction(b.data)?
b.data(f.metaAttr):null;n&&(f=e.extend(f,n));if(f.autostop)f.countdown=f.autostopCount||c.length;var s=b[0];b.data("cycle.opts",f);f.$cont=b;f.stopCount=s.cycleStop;f.elements=c;f.before=f.before?[f.before]:[];f.after=f.after?[f.after]:[];!e.support.opacity&&f.cleartype&&f.after.push(function(){i(this,f)});f.continuous&&f.after.push(function(){q(c,f,0,!f.backwards)});k(f);!e.support.opacity&&f.cleartype&&!f.cleartypeNoBg&&x(g);b.css("position")=="static"&&b.css("position","relative");f.width&&b.width(f.width);
f.height&&f.height!="auto"&&b.height(f.height);if(f.startingSlide)f.startingSlide=parseInt(f.startingSlide,10);else if(f.backwards)f.startingSlide=c.length-1;if(f.random){f.randomMap=[];for(n=0;n<c.length;n++)f.randomMap.push(n);f.randomMap.sort(function(){return Math.random()-0.5});f.randomIndex=1;f.startingSlide=f.randomMap[1]}else if(f.startingSlide>=c.length)f.startingSlide=0;f.currSlide=f.startingSlide||0;var l=f.startingSlide;g.css({position:"absolute",top:0,left:0}).hide().each(function(b){b=
f.backwards?l?b<=l?c.length+(b-l):l-b:c.length-b:l?b>=l?c.length-(b-l):l-b:c.length-b;e(this).css("z-index",b)});e(c[l]).css("opacity",1).show();i(c[l],f);f.fit&&(f.aspect?g.each(function(){var b=e(this),g=f.aspect===!0?b.width()/b.height():f.aspect;f.width&&b.width()!=f.width&&(b.width(f.width),b.height(f.width/g));f.height&&b.height()<f.height&&(b.height(f.height),b.width(f.height*g))}):(f.width&&g.width(f.width),f.height&&f.height!="auto"&&g.height(f.height)));f.center&&(!f.fit||f.aspect)&&g.each(function(){var b=
e(this);b.css({"margin-left":f.width?(f.width-b.width())/2+"px":0,"margin-top":f.height?(f.height-b.height())/2+"px":0})});f.center&&!f.fit&&!f.slideResize&&g.each(function(){var b=e(this);b.css({"margin-left":f.width?(f.width-b.width())/2+"px":0,"margin-top":f.height?(f.height-b.height())/2+"px":0})});if(f.containerResize&&!b.innerHeight()){for(var v=n=0,t=0;t<c.length;t++){var w=e(c[t]),y=w[0],z=w.outerWidth(),A=w.outerHeight();z||(z=y.offsetWidth||y.width||w.attr("width"));A||(A=y.offsetHeight||
y.height||w.attr("height"));n=z>n?z:n;v=A>v?A:v}n>0&&v>0&&b.css({width:n+"px",height:v+"px"})}var B=!1;f.pause&&b.hover(function(){B=!0;this.cyclePause++;a(s,!0)},function(){B&&this.cyclePause--;a(s,!0)});if(m(f)===!1)return!1;var C=!1;d.requeueAttempts=d.requeueAttempts||0;g.each(function(){var b=e(this);this.cycleH=f.fit&&f.height?f.height:b.height()||this.offsetHeight||this.height||b.attr("height")||0;this.cycleW=f.fit&&f.width?f.width:b.width()||this.offsetWidth||this.width||b.attr("width")||
0;if(b.is("img")){var b=e.browser.mozilla&&this.cycleW==34&&this.cycleH==19&&!this.complete,g=e.browser.opera&&(this.cycleW==42&&this.cycleH==19||this.cycleW==37&&this.cycleH==17)&&!this.complete,a=this.cycleH==0&&this.cycleW==0&&!this.complete;if(e.browser.msie&&this.cycleW==28&&this.cycleH==30&&!this.complete||b||g||a)if(j.s&&f.requeueOnImageNotLoaded&&++d.requeueAttempts<100)return h(d.requeueAttempts," - img slide not loaded, requeuing slideshow: ",this.src,this.cycleW,this.cycleH),setTimeout(function(){e(j.s,
j.c).cycle(d)},f.requeueTimeout),C=!0,!1;else h("could not determine size of image: "+this.src,this.cycleW,this.cycleH)}return!0});if(C)return!1;f.cssBefore=f.cssBefore||{};f.cssAfter=f.cssAfter||{};f.cssFirst=f.cssFirst||{};f.animIn=f.animIn||{};f.animOut=f.animOut||{};g.not(":eq("+l+")").css(f.cssBefore);e(g[l]).css(f.cssFirst);if(f.timeout){f.timeout=parseInt(f.timeout,10);if(f.speed.constructor==String)f.speed=e.fx.speeds[f.speed]||parseInt(f.speed,10);f.sync||(f.speed/=2);for(n=f.fx=="none"?
0:f.fx=="shuffle"?500:250;f.timeout-f.speed<n;)f.timeout+=f.speed}if(f.easing)f.easeIn=f.easeOut=f.easing;if(!f.speedIn)f.speedIn=f.speed;if(!f.speedOut)f.speedOut=f.speed;f.slideCount=c.length;f.currSlide=f.lastSlide=l;if(f.random){if(++f.randomIndex==c.length)f.randomIndex=0;f.nextSlide=f.randomMap[f.randomIndex]}else f.nextSlide=f.backwards?f.startingSlide==0?c.length-1:f.startingSlide-1:f.startingSlide>=c.length-1?0:f.startingSlide+1;if(!f.multiFx)if(n=e.fn.cycle.transitions[f.fx],e.isFunction(n))n(b,
g,f);else if(f.fx!="custom"&&!f.multiFx)return h("unknown transition: "+f.fx,"; slideshow terminating"),!1;b=g[l];f.skipInitializationCallbacks||(f.before.length&&f.before[0].apply(b,[b,b,f,!0]),f.after.length&&f.after[0].apply(b,[b,b,f,!0]));f.next&&e(f.next).bind(f.prevNextEvent,function(){return u(f,1)});f.prev&&e(f.prev).bind(f.prevNextEvent,function(){return u(f,0)});(f.pager||f.pagerAnchorBuilder)&&D(c,f);o(f,c);return f}function k(b){b.original={before:[],after:[]};b.original.cssBefore=e.extend({},
b.cssBefore);b.original.cssAfter=e.extend({},b.cssAfter);b.original.animIn=e.extend({},b.animIn);b.original.animOut=e.extend({},b.animOut);e.each(b.before,function(){b.original.before.push(this)});e.each(b.after,function(){b.original.after.push(this)})}function m(b){var g,a,c=e.fn.cycle.transitions;if(b.fx.indexOf(",")>0){b.multiFx=!0;b.fxs=b.fx.replace(/\s*/g,"").split(",");for(g=0;g<b.fxs.length;g++){var i=b.fxs[g];a=c[i];if(!a||!c.hasOwnProperty(i)||!e.isFunction(a))h("discarding unknown transition: ",
i),b.fxs.splice(g,1),g--}if(!b.fxs.length)return h("No valid transitions named; slideshow terminating."),!1}else if(b.fx=="all")for(p in b.multiFx=!0,b.fxs=[],c)a=c[p],c.hasOwnProperty(p)&&e.isFunction(a)&&b.fxs.push(p);if(b.multiFx&&b.randomizeEffects){a=Math.floor(Math.random()*20)+30;for(g=0;g<a;g++)c=Math.floor(Math.random()*b.fxs.length),b.fxs.push(b.fxs.splice(c,1)[0]);d("randomized fx sequence: ",b.fxs)}return!0}function o(b,g){b.addSlide=function(a,c){var d=e(a),f=d[0];b.autostopCount||b.countdown++;
g[c?"unshift":"push"](f);if(b.els)b.els[c?"unshift":"push"](f);b.slideCount=g.length;d.css("position","absolute");d[c?"prependTo":"appendTo"](b.$cont);c&&(b.currSlide++,b.nextSlide++);!e.support.opacity&&b.cleartype&&!b.cleartypeNoBg&&x(d);b.fit&&b.width&&d.width(b.width);b.fit&&b.height&&b.height!="auto"&&d.height(b.height);f.cycleH=b.fit&&b.height?b.height:d.height();f.cycleW=b.fit&&b.width?b.width:d.width();d.css(b.cssBefore);(b.pager||b.pagerAnchorBuilder)&&e.fn.cycle.createPagerAnchor(g.length-
1,f,e(b.pager),g,b);if(e.isFunction(b.onAddSlide))b.onAddSlide(d);else d.hide()}}function q(b,g,a,c){function i(){var a=0;g.timeout&&!g.continuous?(a=t(b[g.currSlide],b[g.nextSlide],g,c),g.fx=="shuffle"&&(a-=g.speedOut)):g.continuous&&f.cyclePause&&(a=10);if(a>0)f.cycleTimeout=setTimeout(function(){q(b,g,0,!g.backwards)},a)}if(a&&g.busy&&g.manualTrump)d("manualTrump in go(), stopping active transition"),e(b).stop(!0,!0),g.busy=0;if(g.busy)d("transition active, ignoring new tx request");else{var f=
g.$cont[0],j=b[g.currSlide],h=b[g.nextSlide];if(!(f.cycleStop!=g.stopCount||f.cycleTimeout===0&&!a))if(!a&&!f.cyclePause&&!g.bounce&&(g.autostop&&--g.countdown<=0||g.nowrap&&!g.random&&g.nextSlide<g.currSlide))g.end&&g.end(g);else{var l=!1;if((a||!f.cyclePause)&&g.nextSlide!=g.currSlide){var l=!0,k=g.fx;j.cycleH=j.cycleH||e(j).height();j.cycleW=j.cycleW||e(j).width();h.cycleH=h.cycleH||e(h).height();h.cycleW=h.cycleW||e(h).width();if(g.multiFx){if(c&&(g.lastFx==void 0||++g.lastFx>=g.fxs.length))g.lastFx=
0;else if(!c&&(g.lastFx==void 0||--g.lastFx<0))g.lastFx=g.fxs.length-1;k=g.fxs[g.lastFx]}if(g.oneTimeFx)k=g.oneTimeFx,g.oneTimeFx=null;e.fn.cycle.resetState(g,k);g.before.length&&e.each(g.before,function(b,a){f.cycleStop==g.stopCount&&a.apply(h,[j,h,g,c])});var m=function(){g.busy=0;e.each(g.after,function(b,a){f.cycleStop==g.stopCount&&a.apply(h,[j,h,g,c])});f.cycleStop||i()};d("tx firing("+k+"); currSlide: "+g.currSlide+"; nextSlide: "+g.nextSlide);g.busy=1;if(g.fxFn)g.fxFn(j,h,g,m,c,a&&g.fastOnEvent);
else if(e.isFunction(e.fn.cycle[g.fx]))e.fn.cycle[g.fx](j,h,g,m,c,a&&g.fastOnEvent);else e.fn.cycle.custom(j,h,g,m,c,a&&g.fastOnEvent)}else i();if(l||g.nextSlide==g.currSlide)if(g.lastSlide=g.currSlide,g.random){g.currSlide=g.nextSlide;if(++g.randomIndex==b.length)g.randomIndex=0;g.nextSlide=g.randomMap[g.randomIndex];if(g.nextSlide==g.currSlide)g.nextSlide=g.currSlide==g.slideCount-1?0:g.currSlide+1}else g.backwards?(a=g.nextSlide-1<0)&&g.bounce?(g.backwards=!g.backwards,g.nextSlide=1,g.currSlide=
0):(g.nextSlide=a?b.length-1:g.nextSlide-1,g.currSlide=a?0:g.nextSlide+1):(a=g.nextSlide+1==b.length)&&g.bounce?(g.backwards=!g.backwards,g.nextSlide=b.length-2,g.currSlide=b.length-1):(g.nextSlide=a?0:g.nextSlide+1,g.currSlide=a?b.length-1:g.nextSlide-1);l&&g.pager&&g.updateActivePagerLink(g.pager,g.currSlide,g.activePagerClass)}}}function t(b,a,e,c){if(e.timeoutFn){for(b=e.timeoutFn.call(b,b,a,e,c);e.fx!="none"&&b-e.speed<250;)b+=e.speed;d("calculated timeout: "+b+"; speed: "+e.speed);if(b!==!1)return b}return e.timeout}
function u(b,a){var c=a?1:-1,d=b.elements,i=b.$cont[0],f=i.cycleTimeout;if(f)clearTimeout(f),i.cycleTimeout=0;if(b.random&&c<0){b.randomIndex--;if(--b.randomIndex==-2)b.randomIndex=d.length-2;else if(b.randomIndex==-1)b.randomIndex=d.length-1;b.nextSlide=b.randomMap[b.randomIndex]}else if(b.random)b.nextSlide=b.randomMap[b.randomIndex];else if(b.nextSlide=b.currSlide+c,b.nextSlide<0){if(b.nowrap)return!1;b.nextSlide=d.length-1}else if(b.nextSlide>=d.length){if(b.nowrap)return!1;b.nextSlide=0}i=b.onPrevNextEvent||
b.prevNextClick;e.isFunction(i)&&i(c>0,b.nextSlide,d[b.nextSlide]);q(d,b,1,a);return!1}function D(b,a){var c=e(a.pager);e.each(b,function(d,i){e.fn.cycle.createPagerAnchor(d,i,c,b,a)});a.updateActivePagerLink(a.pager,a.startingSlide,a.activePagerClass)}function x(b){function a(b){b=parseInt(b,10).toString(16);return b.length<2?"0"+b:b}function c(b){for(;b&&b.nodeName.toLowerCase()!="html";b=b.parentNode){var d=e.css(b,"background-color");if(d&&d.indexOf("rgb")>=0)return b=d.match(/\d+/g),"#"+a(b[0])+
a(b[1])+a(b[2]);if(d&&d!="transparent")return d}return"#ffffff"}d("applying clearType background-color hack");b.each(function(){e(this).css("background-color",c(this))})}if(e.support==void 0)e.support={opacity:!e.browser.msie};e.expr[":"].paused=function(b){return b.cyclePause};e.fn.cycle=function(b,a){var c={s:this.selector,c:this.context};if(this.length===0&&b!="stop"){if(!e.isReady&&c.s)return h("DOM not ready, queuing slideshow"),e(function(){e(c.s,c.c).cycle(b,a)}),this;h("terminating; zero elements found by selector"+
(e.isReady?"":" (DOM not ready)"));return this}return this.each(function(){var i=j(this,b,a);if(i!==!1){i.updateActivePagerLink=i.updateActivePagerLink||e.fn.cycle.updateActivePagerLink;this.cycleTimeout&&clearTimeout(this.cycleTimeout);this.cycleTimeout=this.cyclePause=0;var k=e(this),f=i.slideExpr?e(i.slideExpr,this):k.children(),m=f.get(),s=l(k,f,m,i,c);if(s!==!1)if(m.length<2)h("terminating; too few slides: "+m.length);else if(k=s.continuous?10:t(m[s.currSlide],m[s.nextSlide],s,!s.backwards))k+=
s.delay||0,k<10&&(k=10),d("first timeout: "+k),this.cycleTimeout=setTimeout(function(){q(m,s,0,!i.backwards)},k)}})};e.fn.cycle.resetState=function(b,a){a=a||b.fx;b.before=[];b.after=[];b.cssBefore=e.extend({},b.original.cssBefore);b.cssAfter=e.extend({},b.original.cssAfter);b.animIn=e.extend({},b.original.animIn);b.animOut=e.extend({},b.original.animOut);b.fxFn=null;e.each(b.original.before,function(){b.before.push(this)});e.each(b.original.after,function(){b.after.push(this)});var c=e.fn.cycle.transitions[a];
e.isFunction(c)&&c(b.$cont,e(b.elements),b)};e.fn.cycle.updateActivePagerLink=function(b,a,c){e(b).each(function(){e(this).children().removeClass(c).eq(a).addClass(c)})};e.fn.cycle.next=function(b){u(b,1)};e.fn.cycle.prev=function(b){u(b,0)};e.fn.cycle.createPagerAnchor=function(b,c,i,j,h){e.isFunction(h.pagerAnchorBuilder)?(c=h.pagerAnchorBuilder(b,c),d("pagerAnchorBuilder("+b+", el) returned: "+c)):c='<a href="#">'+(b+1)+"</a>";if(c){var f=e(c);if(f.parents("body").length===0){var l=[];i.length>
1?(i.each(function(){var b=f.clone(!0);e(this).append(b);l.push(b[0])}),f=e(l)):f.appendTo(i)}h.pagerAnchors=h.pagerAnchors||[];h.pagerAnchors.push(f);i=function(a){a.preventDefault();h.nextSlide=b;var a=h.$cont[0],f=a.cycleTimeout;if(f)clearTimeout(f),a.cycleTimeout=0;a=h.onPagerEvent||h.pagerClick;e.isFunction(a)&&a(h.nextSlide,j[h.nextSlide]);q(j,h,1,h.currSlide<b)};/mouseenter|mouseover/i.test(h.pagerEvent)?f.hover(i,function(){}):f.bind(h.pagerEvent,i);!/^click/.test(h.pagerEvent)&&!h.allowPagerClickBubble&&
f.bind("click.cycle",function(){return!1});var k=h.$cont[0],m=!1;h.pauseOnPagerHover&&f.hover(function(){m=!0;k.cyclePause++;a(k,!0,!0)},function(){m&&k.cyclePause--;a(k,!0,!0)})}};e.fn.cycle.hopsFromLast=function(b,a){var e=b.lastSlide,c=b.currSlide;return a?c>e?c-e:b.slideCount-e:c<e?e-c:e+b.slideCount-c};e.fn.cycle.commonReset=function(b,a,c,d,i,f){e(c.elements).not(b).hide();if(typeof c.cssBefore.opacity=="undefined")c.cssBefore.opacity=1;c.cssBefore.display="block";if(c.slideResize&&d!==!1&&
a.cycleW>0)c.cssBefore.width=a.cycleW;if(c.slideResize&&i!==!1&&a.cycleH>0)c.cssBefore.height=a.cycleH;c.cssAfter=c.cssAfter||{};c.cssAfter.display="none";e(b).css("zIndex",c.slideCount+(f===!0?1:0));e(a).css("zIndex",c.slideCount+(f===!0?0:1))};e.fn.cycle.custom=function(b,a,c,d,i,f){var j=e(b),h=e(a),l=c.speedIn,b=c.speedOut,k=c.easeIn,a=c.easeOut;h.css(c.cssBefore);f&&(l=typeof f=="number"?b=f:b=1,k=a=null);var m=function(){h.animate(c.animIn,l,k,function(){d()})};j.animate(c.animOut,b,a,function(){j.css(c.cssAfter);
c.sync||m()});c.sync&&m()};e.fn.cycle.transitions={fade:function(b,a,c){a.not(":eq("+c.currSlide+")").css("opacity",0);c.before.push(function(b,a,c){e.fn.cycle.commonReset(b,a,c);c.cssBefore.opacity=0});c.animIn={opacity:1};c.animOut={opacity:0};c.cssBefore={top:0,left:0}}};e.fn.cycle.ver=function(){return"2.9997"};e.fn.cycle.defaults={activePagerClass:"activeSlide",after:null,allowPagerClickBubble:!1,animIn:null,animOut:null,aspect:!1,autostop:0,autostopCount:0,backwards:!1,before:null,center:null,
cleartype:!e.support.opacity,cleartypeNoBg:!1,containerResize:1,continuous:0,cssAfter:null,cssBefore:null,delay:0,easeIn:null,easeOut:null,easing:null,end:null,fastOnEvent:0,fit:0,fx:"fade",fxFn:null,height:"auto",manualTrump:!0,metaAttr:"cycle",next:null,nowrap:0,onPagerEvent:null,onPrevNextEvent:null,pager:null,pagerAnchorBuilder:null,pagerEvent:"click.cycle",pause:0,pauseOnPagerHover:0,prev:null,prevNextEvent:"click.cycle",random:0,randomizeEffects:1,requeueOnImageNotLoaded:!0,requeueTimeout:250,
rev:0,shuffle:null,skipInitializationCallbacks:!1,slideExpr:null,slideResize:1,speed:1E3,speedIn:null,speedOut:null,startingSlide:0,sync:1,timeout:4E3,timeoutFn:null,updateActivePagerLink:null,width:null}})(jQuery);
(function(e){e.fn.cycle.transitions.none=function(d,h,a){a.fxFn=function(a,d,c,h){e(d).show();e(a).hide();h()}};e.fn.cycle.transitions.fadeout=function(d,h,a){h.not(":eq("+a.currSlide+")").css({display:"block",opacity:1});a.before.push(function(a,d,c,h,k,m){e(a).css("zIndex",c.slideCount+(!m===!0?1:0));e(d).css("zIndex",c.slideCount+(!m===!0?0:1))});a.animIn.opacity=1;a.animOut.opacity=0;a.cssBefore.opacity=1;a.cssBefore.display="block";a.cssAfter.zIndex=0};e.fn.cycle.transitions.scrollUp=function(d,
h,a){d.css("overflow","hidden");a.before.push(e.fn.cycle.commonReset);d=d.height();a.cssBefore.top=d;a.cssBefore.left=0;a.cssFirst.top=0;a.animIn.top=0;a.animOut.top=-d};e.fn.cycle.transitions.scrollDown=function(d,h,a){d.css("overflow","hidden");a.before.push(e.fn.cycle.commonReset);d=d.height();a.cssFirst.top=0;a.cssBefore.top=-d;a.cssBefore.left=0;a.animIn.top=0;a.animOut.top=d};e.fn.cycle.transitions.scrollLeft=function(d,h,a){d.css("overflow","hidden");a.before.push(e.fn.cycle.commonReset);d=
d.width();a.cssFirst.left=0;a.cssBefore.left=d;a.cssBefore.top=0;a.animIn.left=0;a.animOut.left=0-d};e.fn.cycle.transitions.scrollRight=function(d,h,a){d.css("overflow","hidden");a.before.push(e.fn.cycle.commonReset);d=d.width();a.cssFirst.left=0;a.cssBefore.left=-d;a.cssBefore.top=0;a.animIn.left=0;a.animOut.left=d};e.fn.cycle.transitions.scrollHorz=function(d,h,a){d.css("overflow","hidden").width();a.before.push(function(a,d,c,h){c.rev&&(h=!h);e.fn.cycle.commonReset(a,d,c);c.cssBefore.left=h?d.cycleW-
1:1-d.cycleW;c.animOut.left=h?-a.cycleW:a.cycleW});a.cssFirst.left=0;a.cssBefore.top=0;a.animIn.left=0;a.animOut.top=0};e.fn.cycle.transitions.scrollVert=function(d,h,a){d.css("overflow","hidden");a.before.push(function(a,d,c,h){c.rev&&(h=!h);e.fn.cycle.commonReset(a,d,c);c.cssBefore.top=h?1-d.cycleH:d.cycleH-1;c.animOut.top=h?a.cycleH:-a.cycleH});a.cssFirst.top=0;a.cssBefore.left=0;a.animIn.top=0;a.animOut.left=0};e.fn.cycle.transitions.slideX=function(d,h,a){a.before.push(function(a,d,c){e(c.elements).not(a).hide();
e.fn.cycle.commonReset(a,d,c,!1,!0);c.animIn.width=d.cycleW});a.cssBefore.left=0;a.cssBefore.top=0;a.cssBefore.width=0;a.animIn.width="show";a.animOut.width=0};e.fn.cycle.transitions.slideY=function(d,h,a){a.before.push(function(a,d,c){e(c.elements).not(a).hide();e.fn.cycle.commonReset(a,d,c,!0,!1);c.animIn.height=d.cycleH});a.cssBefore.left=0;a.cssBefore.top=0;a.cssBefore.height=0;a.animIn.height="show";a.animOut.height=0};e.fn.cycle.transitions.shuffle=function(d,h,a){d=d.css("overflow","visible").width();
h.css({left:0,top:0});a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!0,!0,!0)});if(!a.speedAdjusted)a.speed/=2,a.speedAdjusted=!0;a.random=0;a.shuffle=a.shuffle||{left:-d,top:15};a.els=[];for(d=0;d<h.length;d++)a.els.push(h[d]);for(d=0;d<a.currSlide;d++)a.els.push(a.els.shift());a.fxFn=function(a,d,c,h,k){c.rev&&(k=!k);var m=k?e(a):e(d);e(d).css(c.cssBefore);var o=c.slideCount;m.animate(c.shuffle,c.speedIn,c.easeIn,function(){for(var d=e.fn.cycle.hopsFromLast(c,k),i=0;i<d;i++)k?c.els.push(c.els.shift()):
c.els.unshift(c.els.pop());if(k){d=0;for(i=c.els.length;d<i;d++)e(c.els[d]).css("z-index",i-d+o)}else d=e(a).css("z-index"),m.css("z-index",parseInt(d,10)+1+o);m.animate({left:0,top:0},c.speedOut,c.easeOut,function(){e(k?this:a).hide();h&&h()})})};e.extend(a.cssBefore,{display:"block",opacity:1,top:0,left:0})};e.fn.cycle.transitions.turnUp=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!0,!1);c.cssBefore.top=d.cycleH;c.animIn.height=d.cycleH;c.animOut.width=d.cycleW});
a.cssFirst.top=0;a.cssBefore.left=0;a.cssBefore.height=0;a.animIn.top=0;a.animOut.height=0};e.fn.cycle.transitions.turnDown=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!0,!1);c.animIn.height=d.cycleH;c.animOut.top=a.cycleH});a.cssFirst.top=0;a.cssBefore.left=0;a.cssBefore.top=0;a.cssBefore.height=0;a.animOut.height=0};e.fn.cycle.transitions.turnLeft=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!1,!0);c.cssBefore.left=d.cycleW;c.animIn.width=
d.cycleW});a.cssBefore.top=0;a.cssBefore.width=0;a.animIn.left=0;a.animOut.width=0};e.fn.cycle.transitions.turnRight=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!1,!0);c.animIn.width=d.cycleW;c.animOut.left=a.cycleW});e.extend(a.cssBefore,{top:0,left:0,width:0});a.animIn.left=0;a.animOut.width=0};e.fn.cycle.transitions.zoom=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!1,!1,!0);c.cssBefore.top=d.cycleH/2;c.cssBefore.left=d.cycleW/2;e.extend(c.animIn,
{top:0,left:0,width:d.cycleW,height:d.cycleH});e.extend(c.animOut,{width:0,height:0,top:a.cycleH/2,left:a.cycleW/2})});a.cssFirst.top=0;a.cssFirst.left=0;a.cssBefore.width=0;a.cssBefore.height=0};e.fn.cycle.transitions.fadeZoom=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!1,!1);c.cssBefore.left=d.cycleW/2;c.cssBefore.top=d.cycleH/2;e.extend(c.animIn,{top:0,left:0,width:d.cycleW,height:d.cycleH})});a.cssBefore.width=0;a.cssBefore.height=0;a.animOut.opacity=0};e.fn.cycle.transitions.blindX=
function(d,h,a){d=d.css("overflow","hidden").width();a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c);c.animIn.width=d.cycleW;c.animOut.left=a.cycleW});a.cssBefore.left=d;a.cssBefore.top=0;a.animIn.left=0;a.animOut.left=d};e.fn.cycle.transitions.blindY=function(d,h,a){d=d.css("overflow","hidden").height();a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c);c.animIn.height=d.cycleH;c.animOut.top=a.cycleH});a.cssBefore.top=d;a.cssBefore.left=0;a.animIn.top=0;a.animOut.top=d};e.fn.cycle.transitions.blindZ=
function(d,h,a){h=d.css("overflow","hidden").height();d=d.width();a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c);c.animIn.height=d.cycleH;c.animOut.top=a.cycleH});a.cssBefore.top=h;a.cssBefore.left=d;a.animIn.top=0;a.animIn.left=0;a.animOut.top=h;a.animOut.left=d};e.fn.cycle.transitions.growX=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!1,!0);c.cssBefore.left=this.cycleW/2;c.animIn.left=0;c.animIn.width=this.cycleW;c.animOut.left=0});a.cssBefore.top=0;a.cssBefore.width=
0};e.fn.cycle.transitions.growY=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!0,!1);c.cssBefore.top=this.cycleH/2;c.animIn.top=0;c.animIn.height=this.cycleH;c.animOut.top=0});a.cssBefore.height=0;a.cssBefore.left=0};e.fn.cycle.transitions.curtainX=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!1,!0,!0);c.cssBefore.left=d.cycleW/2;c.animIn.left=0;c.animIn.width=this.cycleW;c.animOut.left=a.cycleW/2;c.animOut.width=0});a.cssBefore.top=0;a.cssBefore.width=
0};e.fn.cycle.transitions.curtainY=function(d,h,a){a.before.push(function(a,d,c){e.fn.cycle.commonReset(a,d,c,!0,!1,!0);c.cssBefore.top=d.cycleH/2;c.animIn.top=0;c.animIn.height=d.cycleH;c.animOut.top=a.cycleH/2;c.animOut.height=0});a.cssBefore.height=0;a.cssBefore.left=0};e.fn.cycle.transitions.cover=function(d,h,a){var j=a.direction||"left",i=d.css("overflow","hidden").width(),c=d.height();a.before.push(function(a,d,h){e.fn.cycle.commonReset(a,d,h);j=="right"?h.cssBefore.left=-i:j=="up"?h.cssBefore.top=
c:j=="down"?h.cssBefore.top=-c:h.cssBefore.left=i});a.animIn.left=0;a.animIn.top=0;a.cssBefore.top=0;a.cssBefore.left=0};e.fn.cycle.transitions.uncover=function(d,h,a){var j=a.direction||"left",i=d.css("overflow","hidden").width(),c=d.height();a.before.push(function(a,d,h){e.fn.cycle.commonReset(a,d,h,!0,!0,!0);j=="right"?h.animOut.left=i:j=="up"?h.animOut.top=-c:j=="down"?h.animOut.top=c:h.animOut.left=-i});a.animIn.left=0;a.animIn.top=0;a.cssBefore.top=0;a.cssBefore.left=0};e.fn.cycle.transitions.toss=
function(d,h,a){var j=d.css("overflow","visible").width(),i=d.height();a.before.push(function(a,d,h){e.fn.cycle.commonReset(a,d,h,!0,!0,!0);!h.animOut.left&&!h.animOut.top?e.extend(h.animOut,{left:j*2,top:-i/2,opacity:0}):h.animOut.opacity=0});a.cssBefore.left=0;a.cssBefore.top=0;a.animIn.left=0};e.fn.cycle.transitions.wipe=function(d,h,a){var j=d.css("overflow","hidden").width(),i=d.height();a.cssBefore=a.cssBefore||{};var c;a.clip&&(/l2r/.test(a.clip)?c="rect(0px 0px "+i+"px 0px)":/r2l/.test(a.clip)?
c="rect(0px "+j+"px "+i+"px "+j+"px)":/t2b/.test(a.clip)?c="rect(0px "+j+"px 0px 0px)":/b2t/.test(a.clip)?c="rect("+i+"px "+j+"px "+i+"px 0px)":/zoom/.test(a.clip)&&(d=parseInt(i/2,10),h=parseInt(j/2,10),c="rect("+d+"px "+h+"px "+d+"px "+h+"px)"));a.cssBefore.clip=a.cssBefore.clip||c||"rect(0px 0px 0px 0px)";var d=a.cssBefore.clip.match(/(\d+)/g),l=parseInt(d[0],10),k=parseInt(d[1],10),m=parseInt(d[2],10),o=parseInt(d[3],10);a.before.push(function(a,c,d){if(a!=c){var h=e(a),x=e(c);e.fn.cycle.commonReset(a,
c,d,!0,!0,!1);d.cssAfter.display="block";var b=1,g=parseInt(d.speedIn/13,10)-1;(function E(){var a=l?l-parseInt(b*(l/g),10):0,c=o?o-parseInt(b*(o/g),10):0,d=m<i?m+parseInt(b*((i-m)/g||1),10):i,e=k<j?k+parseInt(b*((j-k)/g||1),10):j;x.css({clip:"rect("+a+"px "+e+"px "+d+"px "+c+"px)"});b++<=g?setTimeout(E,13):h.css("display","none")})()}});e.extend(a.cssBefore,{display:"block",opacity:1,top:0,left:0});a.animIn={left:0};a.animOut={left:0}}})(jQuery);

$(function(){
if($("body#home").length){var f,g,b,c,d,a,j;c=0;
b=$("#home0, #home1, #home2");
d=["img/home/IMG_2624.JPG","img/home/IMG_2600.JPG","img/home/IMG_2690.JPG"];
b.first().show();$.backstretch(d[c],{speed:700});$(d).preload();f=function(){var k=b.queue("fx");c=a.attr("rel");$("#slider-controls a").removeClass("showing");a.addClass("showing");$.backstretch(d[c]);k&&k.length===0&&(b.fadeOut(200),$("#home"+c).fadeIn(700));return!1};g=function(){j=setInterval(function(){a=
$("#slider-controls a.showing").next();a.length===0&&(a=$("#slider-controls a:first"));f()},9E3)};$("#slider-controls a").click(function(){a=$(this);clearInterval(j);f();g();return!1});g()}if($("body#store").length){var h=0,i=$("#store-menu"),l=i.offset().top,e=!1;$("#product-photos-holder");var m=$("#store-featured");$(window).scroll(function(){h=$(this).stop().scrollTop();!e&&h>=l?(i.addClass("fixed"),e=!0):e&&h<l&&(i.removeClass("fixed"),e=!1)});m.cycle({fx:"scrollHorz",speed:400,timeout:1E4,pause:1,
slideResize:0,next:"#next-store",prev:"#prev-store"});$("#store-featured-holder").hover(function(){$("#next-store, #prev-store").animate({opacity:1},200)},function(){$("#next-store, #prev-store").animate({opacity:0},200)})}$("#product-photos").length&&($("#product-photos").hover(function(){$("#prod-next, #prod-prev").animate({opacity:1},200)},function(){$("#prod-next, #prod-prev").animate({opacity:0},200)}),$("#product-photos-holder").cycle({fx:"scrollHorz",speed:200,timeout:0,pause:1,slideResize:0,
next:"#prod-next",prev:"#prod-prev",after:function(a,c,b){a=b.currSlide;$("#prod-prev")[a==0?"hide":"show"]();$("#prod-next")[a==b.slideCount-1?"hide":"show"]()}}));$("body#surfboards").length&&$("#surfboard-viewer").cycle({fx:"scrollHorz",speed:500,timeout:1E4,pause:1,slideResize:0,next:"#next-surf",prev:"#prev-surf"});$("body#error_page").length&&$.backstretch("img/error.jpg",{speed:500})});$.fn.preload=function(){this.each(function(){$("<img/>")[0].src=this})};